### ISSUE TITLE
UI: Solve session saving bug on Windows

### ISSUE THREAD

**Issue by rachelt44** [arise-insights/arise-predictions#20]
Sessions are automatically saved to `/tmp` which doesn't exist on Windows, leading to a `No such file or directory` error when running prediction. Current workaround is to manually change the configuration file to a path that exists on the user's machine. Solution should be to automatically store the session in a location that exists (or create it if doesn't exist).

**Comment by eranra** [comment]
@rachelt44 I was thinking if we "always" want that file to be in a temp location we can use the pythonic temp capabilities that are by nature OS agnostic. 

Another option is to look for the token "tmp" and replace it with the windows tmp location. 

Any thoughts on that? any other ideas?

**Comment by rachelt44** [comment]
@eranra I think the first option is best. Something in[ these lines](https://docs.python.org/3/library/tempfile.html).
