### ISSUE TITLE
UI: Move the basis of the path from all configuration variables into an editable text box

### ISSUE THREAD

**Issue by eranra** [arise-insights/arise-predictions#5]

**Comment by eranra** [comment]
![image](https://github.com/user-attachments/assets/3e8cbfa6-25f2-436b-8129-b6e56e564719)

**Comment by eranra** [comment]
Explain: In the above screenshot. For all files that start with "../examples/MLCommons", add a base_path key and make it editable in the top of this screen (also improve the name of the page)

**Comment by rachelt44** [comment]
@eranra rather than calling it `base path`, call it `input path` to be consistent with the terminology used in the command line and documentation.

**Comment by eranra** [comment]
Done / merged

**Comment by rachelt44** [comment]
Merged with this PR: https://github.com/arise-insights/arise-predictions/pull/16
