### ISSUE TITLE
UI: Fix the code for compare with ground thruth code

### ISSUE THREAD

**Issue by eranra** [arise-insights/arise-predictions#8]

**Comment by rachelt44** [comment]
@eranra fix in what way?

**Comment by eranra** [comment]
This is working. The thing is that the prediction "input space" needs to intersect with the original input data. For example in the case of the MLCommons example. For such a configuration::  

```
$ cat config/generated-prediction-config-file.yaml
fixed_values:
  - '# of Accelerators': 8
  - '# of Nodes': 1
  - Accelerator: NVIDIA H100-SXM-80GB
  - Host Processor Core Count: 96
  - Model MLC: gptj-99
  - Processor: AMD EPYC 9654
  - Scenario: Offline
variable_values: []
estimators:
  - target_variable: tokens_per_second
    estimator_file: estimator-nonlinear-XGBoost-Regressor-tokens_per_second.pkl
    greater_is_better: true
```

We see in the UI:


![image](https://github.com/user-attachments/assets/e05ccc7f-a669-48f3-a76e-60b37cae3c09)


Note: The toggle button for "compare with ground truth " is not saved between executions. You need to enable it after restarting the UI !

**Comment by eranra** [comment]
Closing -- not a bug :-)
